listen_ip = '0.0.0.0'

[modbus]
mode = "rtu"
slave_address = 210
timeout = 2

[modbus.rtu]
port = "/dev/ttyUSB0"

[modbus.tcp]
port = 502

[modbus.registers.battery_state_of_charge]
battery_state_of_charge = 167

[modbus.registers.battery_voltage]
battery_v1 = 0
battery_v2 = 1
battery_v3 = 2
battery_v4 = 3
battery_v5 = 4
battery_v6 = 5
battery_v7 = 6
battery_v8 = 7
battery_v9 = 8
battery_v10 = 9
battery_v11 = 10
battery_v12 = 11
